modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "stellarsweeper"
version = "${version}"
displayName = "StellarSweeper"
authors = "StellarVan"
description = '''

'''
logoFile = "assets/stellarsweeper/icon.png"

[[dependencies.stellarsweeper]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.stellarsweeper]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.stellarsweeper]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"
